### ISSUE TITLE
video recording does not work

### ISSUE THREAD

**Issue by nazgee** [bringmeup/hub#23]
full log when pressing 'record' button: [camera.txt](https://github.com/bringmeup/hub/files/1851641/camera.txt)

interesting part
```
03-27 10:55:06.044  1223  1223 V CAM_VideoModule: New video filename: /storage/emulated/0/DCIM/Camera/VID_20180327_105506.3gp.tmp
03-27 10:55:06.117   239  1415 I MediaPlayerService: MediaPlayerService::getOMX
03-27 10:55:06.118   239  1415 I OMXClient: MuxOMX ctor
03-27 10:55:06.118   236   672 I OMXMaster: makeComponentInstance(OMX.Freescale.std.video_encoder.h263.hw-based) in mediacodec process
03-27 10:55:06.120   236   672 I vpu-lib : Product Info: i.MX6Q/D/S
03-27 10:55:06.121   239  1414 I MediaCodec: MediaCodec will operate in async mode
03-27 10:55:06.123   236   672 W OMXNodeInstance: [ec003f:Freescale.std._encoder.h263.hw-based] component does not support metadata mode; using fallback
03-27 10:55:06.123   239  1415 E ACodec  : [OMX.Freescale.std.video_encoder.h263.hw-based] storeMetaDataInBuffers (output) failed w/ err -1010
03-27 10:55:06.128   239  1415 W ACodec  : do not know color format 0x7f000789 = 2130708361
03-27 10:55:06.130   236   236 I OMXPlayer: LEVEL: 1 FUNCTION: GetParameter LINE: 1577
03-27 10:55:06.130   236   236 I OMXPlayer: GetParameter: failure: unsupported index: 0x6000007 
03-27 10:55:06.130   236   236 E OMXNodeInstance: getParameter(ec003f:Freescale.std._encoder.h263.hw-based, ParamVideoErrorCorrection(0x6000007)) ERROR: UnsupportedIndex(0x8000101a)
03-27 10:55:06.130   239  1415 I ACodec  : [OMX.Freescale.std.video_encoder.h263.hw-based] cannot encode color aspects. Ignoring.
03-27 10:55:06.131   239  1415 I ACodec  : [OMX.Freescale.std.video_encoder.h263.hw-based] cannot encode HDR static metadata. Ignoring.
03-27 10:55:06.131   239  1415 I ACodec  : setupVideoEncoder succeeded
03-27 10:55:06.131   236   672 I OMXPlayer: LEVEL: 1 FUNCTION: SetConfig LINE: 1933
03-27 10:55:06.131   236   672 I OMXPlayer: SetConfig: failure: unsupported index: 0x6F800002 
03-27 10:55:06.131   236   672 E OMXNodeInstance: setConfig(ec003f:Freescale.std._encoder.h263.hw-based, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a)
03-27 10:55:06.131   239  1415 I ACodec  : codec does not support config priority (err -1010)
03-27 10:55:06.132   239  1415 W ACodec  : do not know color format 0x7f000789 = 2130708361
03-27 10:55:06.132   236   249 I OMXPlayer: LEVEL: 1 FUNCTION: GetConfig LINE: 1828
03-27 10:55:06.132   236   249 I OMXPlayer: GetConfig: failure: unsupported index: 0x6F60000A 
03-27 10:55:06.132   236   249 E OMXNodeInstance: getConfig(ec003f:Freescale.std._encoder.h263.hw-based, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
03-27 10:55:06.132   236   236 I OMXPlayer: LEVEL: 1 FUNCTION: GetParameter LINE: 1577
03-27 10:55:06.132   236   236 I OMXPlayer: GetParameter: failure: unsupported index: 0x6000006 
03-27 10:55:06.132   236   236 E OMXNodeInstance: getParameter(ec003f:Freescale.std._encoder.h263.hw-based, ParamVideoIntraRefresh(0x6000006)) ERROR: UnsupportedIndex(0x8000101a)
03-27 10:55:06.135   236   249 I vpu-lib : <gpu> alloc handle: 0xb2b8f0f0, paddr: 0x2b3e9000, vaddr: 0xaa16f000
03-27 10:55:06.136   236   236 I vpu-lib : <gpu> alloc handle: 0xb2b8f270, paddr: 0x2b3eb000, vaddr: 0xaa171000
03-27 10:55:06.140   236   672 I vpu-lib : <gpu> alloc handle: 0xb2e6c320, paddr: 0x2c218000, vaddr: 0xaaf9e000
03-27 10:55:06.142   236   249 I vpu-lib : <gpu> alloc handle: 0xb2b8f0a0, paddr: 0x2c319000, vaddr: 0xab09f000
03-27 10:55:06.143   236   236 I vpu-lib : <gpu> alloc handle: 0xb2e6c3b0, paddr: 0x2c41a000, vaddr: 0xab1a0000
03-27 10:55:06.145   239   239 E AudioSystem: AudioSystem::getInputBufferSize failed sampleRate 8000 format 0x1 channelMask 10
03-27 10:55:06.145   239   239 E AudioRecord: AudioSystem could not query the input buffer size for sampleRate 8000, format 0x1, channelMask 0x10; status -22
03-27 10:55:06.145   239   239 E StagefrightRecorder: audio source is not initialized
03-27 10:55:06.146   239   239 D MPEG4Writer: Video track stopping
03-27 10:55:06.146   239   239 E MPEG4Writer: Stop() called but track is not started
03-27 10:55:06.146  1223  1223 E MediaRecorder: start failed: -2147483648
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: Could not start media recorder. 
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: java.lang.RuntimeException: start failed.
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.media.MediaRecorder.start(Native Method)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at com.android.camera.VideoModule$11.onStorageUpdateDone(VideoModule.java:1397)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2351)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2346)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.os.AsyncTask.finish(AsyncTask.java:667)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.os.Looper.loop(Looper.java:154)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-27 10:55:06.147  1223  1223 E CAM_VideoModule: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: Handling Camera Access Failure:
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: java.lang.Exception
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:84)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at com.android.camera.VideoModule$11.onStorageUpdateDone(VideoModule.java:1400)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2351)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2346)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at android.os.AsyncTask.finish(AsyncTask.java:667)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at android.os.Looper.loop(Looper.java:154)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-27 10:55:06.148  1223  1223 E CAM_FatalErrorHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-27 10:55:06.148  1223  1223 E CAM_CameraUtil: Show fatal error dialog
```

**Comment by nazgee** [comment]
probabaly caused by ``PLL unlocking`` https://github.com/bringmeup/hub/issues/24
